stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw/deliverytime.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/delivery_cleaned.csv
  data_preparation:
    cmd: python src/data/data_preparation.py
    deps:
    - data/cleaned/delivery_cleaned.csv
    - src/data/data_preparation.py
    params:
    - data_preparation.random_state
    - data_preparation.test_size
    outs:
    - data/interim/test.csv
    - data/interim/train.csv
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/interim/test.csv
    - data/interim/train.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/test_trans.csv
    - data/processed/train_trans.csv
    - models/preprocessor.joblib
  model_training:
    cmd: python src/model/model_train.py
    deps:
    - data/processed/train_trans.csv
    - src/model/model_train.py
    params:
    - model_train.LightGBM
    outs:
    - models/model.joblib
    - models/power_transformer.joblib
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed/test_trans.csv
    - data/processed/train_trans.csv
    - models/model.joblib
    - src/model/model_evaluation.py
    outs:
    - run_information.json
